! Ceremony class methodsFor: 'creation' !
new: ceroption
	^(super new: ceroption) initcer
!!

"============================================"
! Ceremony  methodsFor: 'creation' !
initcer
	length := 0
!!

"============================================"
! Ceremony  methodsFor: 'accessing' !
length
	^length
!!

"============================================"
! Ceremony  methodsFor: 'setting' !
length: l
	length := l
!!
