! Ceremony class methodsFor: 'creation' !
new: ceroption
	^(super new: ceroption) init 
!!

"============================================"
! Ceremony  methodsFor: 'creation' !
init
	length := 0.
!!

"============================================"
! Ceremony  methodsFor: 'accessing' !
length
	^length
!!

"============================================"
! Ceremony  methodsFor: 'setting' !
length: l
	length := l.
!!
