|f|
App reset; asynchronousOff.
f := Factory new: 'f1'.
President worksIn: f.
Historian worksIn: f.
Senator worksIn: f.
Senator worksIn: f.
Senator worksIn: f.
Senator worksIn: f.
Senator worksIn: f.
Senator worksIn: f.
Senator worksIn: f.
Senator worksIn: f.
Senator worksIn: f.
Senator worksIn: f.
Senator worksIn: f.
Senator worksIn: f.
Senator worksIn: f.
Senator worksIn: f.
Senator worksIn: f.
Senator worksIn: f.
Senator worksIn: f.
Senator worksIn: f.
Senator worksIn: f.
Senator worksIn: f.

f run.
!
