|f|
App reset; asynchronousOff.
f := Factory new: 'f2'.
Senator worksIn: f.
Senator worksIn: f.
Senator worksIn: f.
Senator worksIn: f.
Senator worksIn: f.
Senator worksIn: f.
Senator worksIn: f.
Senator worksIn: f.
Senator worksIn: f.
Senator worksIn: f.
Senator worksIn: f.
Senator worksIn: f.
Senator worksIn: f.
Senator worksIn: f.
Senator worksIn: f.
Senator worksIn: f.
Senator worksIn: f.
Senator worksIn: f.
Senator worksIn: f.
Senator worksIn: f.

f run.
!
